spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wecare
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
#jwt secret key
jwt:
  secret: BEEDFB5129AD1AEBEE6E8C4FA450B30637B0C8BD7289B6CAB56BB11A0586FE7A545553676E88F494120A854ADA7B0EBDE48403A9198050C0318399C611D2BC40
  expiration: 1800000